SAP/vscode-mta-tools

package.json

build: add Code Coverage Report

---

package.json
src/utils/utils.ts
tests/commands/mtaBuildCommand.spec.ts
tests/commands/mtarDeployCommand.spec.ts
tests/mockUtil.ts
tests/utils/utils.spec.ts

test: unskip tests

---

package-lock.json
package.json
src/commands/mtaBuildCommand.ts
src/commands/mtarDeployCommand.ts
src/extension.ts
src/i18n/messages.ts
src/logger/logger-wrapper.ts
src/logger/settings-changes-handler.ts
src/logger/settings.ts
tests/commands/mtaBuildCommand.spec.ts
tests/commands/mtarDeployCommand.spec.ts
tests/extension.spec.ts
tests/mockUtil.ts

feat: add logging framework and logs

---

src/commands/mtaBuildCommand.ts

fix: fix space in project name

---

README.md
package.json
src/commands/addModuleCommand.ts
src/commands/mtaBuildCommand.ts
src/commands/mtarDeployCommand.ts
src/extension.ts
src/i18n/messages.ts
src/utils/utils.ts
tests/commands/addModuleCommand.spec.ts
tests/commands/mtaBuildCommand.spec.ts
tests/commands/mtarDeployCommand.spec.ts
tests/extension.spec.ts

Add command for opening 'add module' wizard

---

CHANGELOG.md
package-lock.json
package.json

Modulerelease

---

package.json

fix: update command name

---

src/i18n/messages.ts

fix: update module generation message

---

package.json

Add schema configuration for mta.yaml, mtad.yaml and *.mtaext

chore: add schemas config

---

package-lock.json
package.json
src/commands/addModuleCommand.ts
src/commands/mtaBuildCommand.ts
src/commands/mtarDeployCommand.ts
src/extension.ts
src/i18n/messages.ts
tests/commands/addModuleCommand.spec.ts
tests/commands/mtaBuildCommand.spec.ts
tests/commands/mtarDeployCommand.spec.ts
tests/extension.spec.ts

refactor: add usage analytics

---

.gitignore

add reuse and LICENSES to gitignore

---

.mocharc.json
mocha.opts
nyc.config.js
package-lock.json
package.json
src/commands/addModuleCommand.ts
src/commands/mtaBuildCommand.ts
src/commands/mtarDeployCommand.ts
src/extension.ts
src/i18n/messages.ts
src/logger/logger-wrapper.ts
src/logger/settings-changes-handler.ts
src/logger/settings.ts
src/utils/selectionItem.ts
src/utils/utils.ts
tests/commands/mtaBuildCommand.spec.ts
tests/commands/mtarDeployCommand.spec.ts
tests/extension.spec.ts
tests/mockUtil.ts
tests/utils/selectionItem.spec.ts
tests/utils/utils.spec.ts
tsconfig.json

fix: remove mocha.opts, adjust tsconfig.json and fix ts issues

---

.vscodeignore
package-lock.json
package.json
webpack.config.js

chore: vsix bundling

---

package.json
src/logger/logger-wrapper.ts

chore: update logger to v1.2.0

---

.circleci/config.yml
README.md
package.json

chore: add coveralls

---

package.json

upgrade vscode-logging/logger:1.2.1

---

src/commands/mtarDeployCommand.ts
tests/commands/mtarDeployCommand.spec.ts

fix: handle path with space

---

README.md

docs: lgtm badge

---

package-lock.json
package.json

build(deps): bump @sap/swa-for-sapbas-vsx from 1.1.0 to 1.1.9

---

src/validations/mta/mtaDiagnostic.ts
src/validations/mta/mtaValidations.ts
tests/validations/mta/mtaValidations.spec.ts

test: mta.yaml and dev.mtaext validations in the problem view - unit test completion 
adding tests for
https://github.com/SAP/vscode-mta-tools/pull/165/files/601d2d6ba3793fefbcff11cdf18d93935a236265..47a63a1d1a0c8873477d42cf32ae69ae1f8a578c#diff-1cc98a3034c98a6414be4eb21ac2e16f712f3ee68ff279b39e19e0ec98b51802

test: validations in the problem view - unit test completion 

---

package.json

fix: remove vscode.yaml dependency

---

package.json
src/i18n/messages.ts

chore: change MBT Build command title

---

CHANGELOG.md
package-lock.json
package.json

chore: handle security issue

---

README.md

doc: add licensing section

---

package-lock.json
package.json
src/commands/mtarDeployCommand.ts
src/i18n/messages.ts
src/task-providers/utils/cfutil.ts
src/utils/utils.ts
tests/commands/mtarDeployCommand.spec.ts
tests/mockUtil.ts
tests/utils/utils.spec.ts

fix: login to CF before deploying mtar

---

CHANGELOG.md

chore: format

---

src/commands/mtarDeployCommand.ts
src/utils/utils.ts
tests/utils/utils.spec.ts

fix: fix cf login pop up when user is logged in to cf

---

package-lock.json
package.json

chore: bump mta-lib version to 1.7.4

---

.circleci/config.yml

upgrade circle-ci deploy node go version and ghr install command

upgrade circle-ci deploy node go version and ghr install command

---

.circleci/config.yml
.vscodeignore
github-rel-env/package.json
package.json

Support publish vscode-mta-tools to npmjs

Support publish vscode-mta-tools to npmjs 

---

.circleci/config.yml
npmjs-pub-env/package.json

support publish vscode-mta-tool to npmjs under @sap_oss scope

support publish vscode-mta-tool to npmjs under @sap_oss scope
